# Generated by Django 5.2.13 on 2026-04-10 08:09

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_initial'),
    ]

    operations = [
        # 1. Wipe all order-related data (can't cast bigint -> uuid in-place)
        migrations.RunSQL(
            "TRUNCATE orders_payment, orders_orderitem, orders_order CASCADE;",
            reverse_sql=migrations.RunSQL.noop,
        ),
        # 2. Drop the old integer PK and rebuild as UUID
        migrations.RunSQL(
            sql="""
                -- Drop FK constraints that reference orders_order.id
                ALTER TABLE orders_orderitem DROP CONSTRAINT IF EXISTS orders_orderitem_order_id_fe61a34d_fk_orders_order_id;
                ALTER TABLE orders_payment   DROP CONSTRAINT IF EXISTS orders_payment_order_id_bdccf250_fk_orders_order_id;

                -- Swap PK column on orders_order
                ALTER TABLE orders_order DROP CONSTRAINT orders_order_pkey;
                ALTER TABLE orders_order DROP COLUMN id;
                ALTER TABLE orders_order ADD COLUMN id uuid NOT NULL DEFAULT gen_random_uuid() PRIMARY KEY;

                -- Swap FK column on orders_orderitem
                ALTER TABLE orders_orderitem DROP COLUMN order_id;
                ALTER TABLE orders_orderitem ADD COLUMN order_id uuid;

                -- Swap FK column on orders_payment
                ALTER TABLE orders_payment DROP COLUMN order_id;
                ALTER TABLE orders_payment ADD COLUMN order_id uuid UNIQUE;
            """,
            reverse_sql=migrations.RunSQL.noop,
        ),
        # 3. Tell Django's migration state that the field is now a UUIDField
        migrations.AlterField(
            model_name='order',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
