"""create auctions table

Revision ID: 5fcbbf36b920
Revises: 1ba6384ee5a1
Create Date: 2026-02-24 14:48:23.016496

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql
import sqlmodel

# revision identifiers, used by Alembic.
revision: str = '5fcbbf36b920'
down_revision: Union[str, Sequence[str], None] = '1ba6384ee5a1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('auctions', 'description',
               existing_type=mysql.VARCHAR(length=1024),
               type_=sqlmodel.sql.sqltypes.AutoString(),
               existing_nullable=True)
    op.alter_column('bids', 'created_at',
               existing_type=mysql.DATETIME(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('bids', 'created_at',
               existing_type=mysql.DATETIME(),
               nullable=False)
    op.alter_column('auctions', 'description',
               existing_type=sqlmodel.sql.sqltypes.AutoString(),
               type_=mysql.VARCHAR(length=1024),
               existing_nullable=True)
    # ### end Alembic commands ###
